global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "netshield-traffic-detector"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["netshield-app:8000"]
