apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netshield-storage-pvc
  labels:
    app: netshield-ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
