apiVersion: v1
kind: Service
metadata:
  name: netshield-service
  labels:
    app: netshield-ai
spec:
  type: ClusterIP
  selector:
    app: netshield-ai
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: netshield-nodeport
  labels:
    app: netshield-ai
spec:
  type: NodePort
  selector:
    app: netshield-ai
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
      protocol: TCP
