apiVersion: v1
kind: ServiceAccount
metadata:
  name: netshield-sa
  labels:
    app: netshield-ai
    tier: api-ml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: netshield-role
  labels:
    app: netshield-ai
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: netshield-rolebinding
  labels:
    app: netshield-ai
subjects:
  - kind: ServiceAccount
    name: netshield-sa
roleRef:
  kind: Role
  name: netshield-role
  apiGroup: rbac.authorization.k8s.io
