apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve-model-sa
  labels:
    app: netshield-ai
    tier: kserve-predictor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kserve-model-role
  labels:
    app: netshield-ai
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims", "secrets", "configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kserve-model-rolebinding
  labels:
    app: netshield-ai
subjects:
  - kind: ServiceAccount
    name: kserve-model-sa
roleRef:
  kind: Role
  name: kserve-model-role
  apiGroup: rbac.authorization.k8s.io
